sonar.organization=nicholasmathias197
sonar.projectKey=nicholasmathias197_assetmind
sonar.projectName=assetmind
sonar.sources=assetmind/assetmind-api/src/main/java,assetmind/assetmind-core/src/main/java,assetmind/assetmind-infrastructure/src/main/java,assetmind/assetmind-application/src/main/java,assetmind/assetmind-ai/src/main/java,assetmind/assetmind-batch/src/main/java
sonar.tests=assetmind/assetmind-application/src/test/java,assetmind/assetmind-ai/src/test/java,assetmind/assetmind-core/src/test/java
sonar.java.binaries=assetmind/assetmind-application/target/classes,assetmind/assetmind-api/target/classes,assetmind/assetmind-core/target/classes,assetmind/assetmind-infrastructure/target/classes,assetmind/assetmind-ai/target/classes,assetmind/assetmind-batch/target/classes
sonar.sourceEncoding=UTF-8
